version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 12
    commands:
  pre_build:
    commands:
      - if [ "$Validate" != "true" ]; then aws s3 cp $S3HomePath ~ --recursive; fi
      - npm ci
  build:
    commands:
      - npm run test
      - if [ "$Validate" != "true" ]; then npm publish --access public; fi
      